apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-on-next-bus
spec:
  schedule: "*/1 0,7-23 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: next-bus
            image: gcr.io/octranspo-190317/octranspo:latest
            args: ["python", "run.py"]
          restartPolicy: OnFailure
