# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  config: |
    artifactRepository:
      s3:
        bucket: argo-octranspo-190317
        endpoint: storage.googleapis.com
        accessKeySecret:
          name: argo-octranspo-190317-gcs-creds
          key: accessKey
        secretKeySecret:
          name: argo-octranspo-190317-gcs-creds
          key: secretKey
    executorImage: argoproj/argoexec:v2.1.0
kind: ConfigMap
metadata:
  creationTimestamp: 2018-05-24T18:04:46Z
  name: workflow-controller-configmap
  namespace: kube-system
  resourceVersion: "12200729"
  selfLink: /api/v1/namespaces/kube-system/configmaps/workflow-controller-configmap
  uid: f17c8bd3-5f7c-11e8-a75d-42010a8000de